Models/ViewModels/HomeViewModel.cs
using System.Collections.Generic;

namespace SimpleCRUDGridWebApp.Models.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Expense> Expenses { get; set; }
    }
}

Controllers/EditController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SimpleCRUDGridWebApp.Models;
using SimpleCRUDGridWebApp.Models.ViewModels;
using SimpleCRUDGridWebApp.Services;

namespace SimpleCRUDGridWebApp.Controllers
{
    public class EditController : Controller
    {
        private ISqlGridData _data;
        private List<SelectListItem> _customers, _projects;

        public EditController(ISqlGridData data)
        {
            _data = data;
        }

        public IActionResult Index(int id)
        {
            EditExpenseVM editExpense = new EditExpenseVM();

            Expense currentExpense = new Expense();
            currentExpense = _data.GetExpense(id);
            editExpense.customerId = currentExpense.Project.Customer.CustomerId;
            editExpense.projectId = currentExpense.Project.ProjectId;
            editExpense.expenseId = currentExpense.ExpenseId;
            editExpense.expenseName = currentExpense.ExpenseName;
            editExpense.expenseDate = currentExpense.ExpenseDate;
            editExpense.expenseDescription = currentExpense.Description;
            editExpense.expenseAmount = currentExpense.Amount;
            editExpense.customers = new List<SelectListItem>();
            editExpense.projects = new List<SelectListItem>();

            FillDropDownLists(ref _customers, ref _projects, editExpense.customerId);

            editExpense.customers = _customers;
            editExpense.projects = _projects;

            return View(editExpense);
        }

        private void FillDropDownLists(ref List<SelectListItem> customers, ref List<SelectListItem> projects, int id)
        {
            customers = new List<SelectListItem>();
            customers.Add(new SelectListItem { Text = "Select a customer" });
            foreach (Customer cust in _data.GetCustomers())
            {
                customers.Add(new SelectListItem
                {
                    Text = cust.CustomerName,
                    Value = cust.CustomerId.ToString()
                });
            }

            projects = new List<SelectListItem>();
            projects.Add(new SelectListItem { Text = "Select a project" });
            foreach (Project proj in _data.GetProjects(id))
            {
                projects.Add(new SelectListItem
                {
                    Text = proj.ProjectName,
                    Value = proj.ProjectId.ToString()
                });
            }
        }

        [HttpPostAttribute]
        public IActionResult SaveForm(EditExpenseVM editExpense, string btnSave)
        {
            if (ModelState.IsValid)
            {
                Expense modifiedExpense = new Expense();
                modifiedExpense = _data.GetExpense(editExpense.expenseId);
                modifiedExpense.Amount = editExpense.expenseAmount;
                modifiedExpense.ExpenseName = editExpense.expenseName;
                modifiedExpense.ExpenseId = editExpense.expenseId;
                modifiedExpense.Description = editExpense.expenseDescription;
                modifiedExpense.ProjectId = editExpense.projectId;

                _data.UpdateExpense(modifiedExpense);

                if (btnSave.ToLower() == "save")
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            FillDropDownLists(ref _customers, ref _projects, editExpense.customerId);
            editExpense.customers = _customers;
            editExpense.projects = _projects;

            return View("Index", editExpense);
        }

        [HttpGetAttribute]
        public JsonResult GetProjects(int id)
        {
            return new JsonResult(_data.GetProjects(id));
        }

        [HttpGetAttribute]
        public JsonResult GetExpense()
        {
            return new JsonResult(_data.GetExpense(1));
        }


    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SimpleCRUDGridWebApp.Models;
using SimpleCRUDGridWebApp.Models.ViewModels;
using SimpleCRUDGridWebApp.Services;

namespace SimpleCRUDGridWebApp.Controllers
{
    public class HomeController : Controller
    {
        private ISqlGridData _sqlData;
        public string sortOrder { get; set; }
        //private UnitOfWork unitOfWork;
        public HomeController(ISqlGridData sqlData/*, UnitOfWork unitOfWork*/)
        {
             //this.unitOfWork = unitOfWork;
            _sqlData = sqlData;
        }

        public IActionResult Index()
        {
            HomeViewModel viewModel = new HomeViewModel();
            viewModel.Expenses = _sqlData.GetExpenses();
            //viewModel.Expenses = this.unitOfWork.ExpenseRepository.Get(includeProperties: "Project, Customer");
            return View(viewModel);
        }

       /* public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }*/

        public IActionResult Delete(int id)
        {
            _sqlData.DeleteExpense(id);
            return RedirectToAction("Index", "Home");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}


Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewBag.Title = "Home Page";
}

<table id="grid" name="grid" class="table table-striped table-bordered" >
    <thead>
            <tr>
                <th></th>
                <th>Date</th>
                <th>Customer</th>
                <th>Project</th>
                <th>Amount</th>
                <th></th>
            </tr>
        </thead>
<tbody>
    @foreach(var exp in Model.Expenses)
    {
        <tr>
            <td>
                <a asp-controller="Edit" asp-route-id="@exp.ExpenseId">edit</a>
            </td>
            <td>
            @exp.ExpenseDate
        </td>
        <td>
            @exp.Project.Customer.CustomerName
        </td>
        <td>
            @exp.Project.ProjectName
        </td>
        <td>
            @exp.Amount
        </td>
        <td>
            <a data-toggle="modal" data-target="#exampleModal" href="#" data-expid="@exp.ExpenseId">delete</a>
            <!-- <a asp-action="Delete" asp-route-id="@exp.ExpenseId">delete</a> -->
        </td>
        </tr>
    }
</tbody>
</table> 

<div class="modal" tabindex="-1" role="dialog" id="exampleModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete?</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" id="btnYesDelete">Yes</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>


<script type="text/javascript">
    $(document).ready(function() {
    var table = $('#grid').DataTable(
        {
             "order": [[1, 'desc']],
            "columns":[{"orderable": false}, null, null, null, null, {"orderable": false}]
         });
    $( "input[type='search']").addClass( "form-control" ).attr("placeholder", "type to search");
    //$( "#grid_filter").addClass( "form-group form-inline" )
    $( "#grid_filter").append("<button type='button' class='btn btn-danger' style='margin-left:15px;' id='btnClearFilter' name='btnClearFilter'>Clear</button>")
    .append("<a class='btn btn-success' style='margin-left:15px;' id='btnAdd' href='/Create' name='btnAdd'>Add</a>");
    $('#grid_wrapper').attr('style', 'width:100%;margin-top:5%;');

    $('#exampleModal').on('show.bs.modal', function (event) {
        var button  = $(event.relatedTarget);
        var buttonData = button.data('expid');
        $('#btnYesDelete').attr('href', '/Home/Delete/' + buttonData);
    });

$("#btnClearFilter").click(function(){
        $("input[type='search']").val('');
        /*var table = $('#grid').DataTable();*/
        //table.draw();
    });
} );


</script>